name: pytest # 定義workflow
# on: [push, workflow_dispatch] # 如何觸發workflow, dispatch手動的(event), push會觸發action

# 多個event, 指定某個filter或types
on: 
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request: # 第三個event
    types: [opened] # 如果有人open了一個pull request, 就會觸發workflow
  # schedule:
  #   - cron: '*/5 * * * *' # run every 5 mins


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps: 
      - name: print github action context
        run: echo ${{ github.repositoryUrl }}
      # 印出當前folder路徑, 及所有的files
      - name: pre - checkout
        run: | 
          pwd 
          ls -lh
      # step1: clone repo on current path and run the test
      # - name: clone repository
      #   run: |
      #     git clone https://github.com/revatsai/github-actions-python.git
      #     cd github-actions-python
      # github action寫好的指令，可以直接使用
      - name: checkout code
        uses: actions/checkout@v4 
      - name: after checkout
        run: |
          pwd
          ls -lh
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
